apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: testapp-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: testapp
    spec:
      containers:
      - name: testapp
        image: iamdockeruser/tomcat-app:latest
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: testapp-service
spec:
  type: NodePort
  ports:
    - nodePort: 31357
      port: 8081
      protocol: TCP
      targetPort: 8080
  selector:
    app: testapp
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: testapp-ingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /testapp
        backend:
          serviceName: testapp-service
          servicePort: 8081
